docs/reference/symbols.rst
dwave/optimization/mathematical.py
dwave/optimization/model.pxd
dwave/optimization/model.pyi
dwave/optimization/model.pyx
dwave/optimization/symbols.pyx
tests/test_model.py

I think these names are much clearer.
These are both "internal" classes, in that users should not interact with them directly except via their subclasses. So I don't believe this will break any testing code.

Rename NodeObserver to Symbol and ArrayObserver to ArraySymbol

---

pyproject.toml

See https://github.com/dwavesystems/dwave-preprocessing/pull/131, https://github.com/adang1345/delvewheel/issues/38.
Should fix the errors in https://github.com/dwavesystems/dwave-system/pull/518 once it's deployed.

Fix use of delvewheel with a namespace package

---

docs/sdk_index.rst

Using the index directly in the SDK doesn't look so good (`dwave-samplers` does that but it pulls a lot from the README):

Add sdk_index file

---

dwave/optimization/model.pyx
releasenotes/notes/add-num_edges-4569f47ca86590de.yaml
tests/test_generators.py

Closes https://github.com/dwavesystems/dwave-optimization/issues/28

Add a method for calculating num_edges

---

dwave/optimization/generators.py
tests/test_generators.py

Added support for asymmetric square distance arrays for the CVRP generator. This allows for distances to have direction. The most obvious use case is with one way roads, but it's probably the case that most roads are slightly different length depending on the direction.
Let me know if I should add release notes (not exactly sure how those work) or more tests.

Support asymmetric square arrays for CVRP generator

---

dwave/optimization/src/nodes/collections.cpp
releasenotes/notes/fix-disjointbitset-state-copy-0f1760e77330ba6d.yaml
tests/cpp/tests/test_nodes_collections.cpp

I'll think about ways to enforce that all decision nodes have copyable states in the future. But for now let's fix the current one.

Fix `DisjointBitSetsNode` state copying

---

dwave/optimization/__init__.py
dwave/optimization/model.pxd
dwave/optimization/model.pyx
dwave/optimization/symbols.pyx
releasenotes/notes/refactor-node-discovery-f468e7dc54fcfbdc.yaml

Change the way that the library creates nodes from either raw pointers or their names.
The main change is removing the enormous `if`/`else` statement in `symbol_from_ptr()` and replace it with an approach that uses [typeid()](https://en.cppreference.com/w/cpp/language/typeid). This makes `symbol_from_ptr()` take ~66% less time in benchmarks on my system. It's also less of a maintenance nightmare.
The cost however is that now each node must be registered, with a new private `_register()` function. I'd like to automate that with something like [__init_subclass__](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__), but as far as I can tell, Cython doesn't have any mechanism that gets called when a class is defined. Or any support for metaclasses etc.

Refactor node discovery

---

dwave/optimization/generators.py
dwave/optimization/mathematical.py
releasenotes/notes/mathematical-typing-fd454b6bce48d9e5.yaml
tests/test_examples.py
tests/test_symbols.py

Also remove unneeded whitespace and tweak the input argument names and accepted types.
The arg name changes were chosen to be more consistent with NumPy, e.g. [add()](https://numpy.org/doc/stable/reference/generated/numpy.add.html).

Add missing typing to dwave.optimization.mathematical

---

.circleci/config.yml
docs/conf.py
docs/index.rst
docs/intro.rst
docs/requirements.txt
dwave/optimization/model.pyx
dwave/optimization/symbols.pyx

Match the SDK's doc theme and add doctests to CI.
Closes https://github.com/dwavesystems/dwave-optimization/issues/54
Also fixes some doc errors introduced in #42 and #53

Improve doc testing

---

tests/test_symbols.py

Remove the symbol test mixins and replace them with subclasses. This requires putting them in another "namespace". I also added `BinaryOpTests` with a single sanity test.

Restructure symbol tests

---

docs/conf.py
docs/reference/generators.rst
dwave/optimization/generators.py

The main benefit here is that new generators are automatically incorporated into the docs. For example, we were already missing `quadratic_assignment`.
The cons are slightly ugly formatting at the top level 
and no navigation within the page on the sidebar 
IMO the maintenance benefit is worth it. If we wanted a summary table at the top, there are sphinx plugins, e.g. https://github.com/Chilipp/autodocsumm.
Another change made is that by using `autodoc_type_aliases` we can significantly shrink the size and increase the readability of the signature. IMO we should make that change in the SDK.

Flatten generator docs

---

docs/reference/math.rst
dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/libcpp/nodes.pxd
dwave/optimization/mathematical.py
dwave/optimization/src/nodes/mathematical.cpp
dwave/optimization/symbols.pyi
dwave/optimization/symbols.pyx
releasenotes/notes/unary-nodes-refresh-e60c3850212ee7d6.yaml
tests/cpp/tests/test_nodes_mathematical.cpp
tests/test_symbols.py

There isn't really an analogue to `Logical` in NumPy, it does either `np.asarray(x, dtype=bool)` or `x != 0`. I chose `logical(x)` to follow NumPy's `logical_and(array)`, `logical_not(array)`, etc convention. Open to other names.
I also implemented some missing `UnaryOpNode` methods. Probably there are similar things we need to do for `NaryOpNode` and `BinaryOpNode`.

Implement `Logical` and `Not` symbols

---

.circleci/config.yml
dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
dwave/optimization/src/nodes/testing.cpp
pyproject.toml
requirements.txt

This fixes an issue introduced by a backwards compatibility break in setuptools 72.1.0.
Thanks @randomir for finding the bug.

Use CPPFLAGS rather than CFLAGS in CI

---

dwave/optimization/src/nodes/_state.hpp
dwave/optimization/src/nodes/flow.cpp
dwave/optimization/src/nodes/indexing.cpp
dwave/optimization/src/nodes/mathematical.cpp
dwave/optimization/src/nodes/numbers.cpp

I tried to minimize the changes, so there is definitely more we could do, but this should reduce some of the code duplication as well as provide a centralized place for bug fixes and/or performance updates.
The main cost is that now all of the non-dynamic nodes keep a redundant `ssize_t previous_size_` on their state, plus the very minor runtime cost of checking it. We could avoid that with templates, but IMO the extra complexity isn't worth it.

Add helper class for node states

---

.circleci/config.yml

See https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177

Use default linux arm machine in CircleCI

---

dwave/optimization/src/nodes/indexing.cpp
dwave/optimization/src/nodes/numbers.cpp
dwave/optimization/src/nodes/testing.cpp

Discovered while messing around with building tests with `meson`. Have not activated `_GLIBCXX_ASSERTIONS` in CI yet, will do that in a followup PR (pending decisions on tests-with-`meson`).

Fix assertion errors seen with `_GLIBCXX_ASSERTIONS`

---

dwave/optimization/generators.py
dwave/optimization/model.pyx
releasenotes/notes/fix-combined-indexing-with-integers-d6203f3865864769.yaml
tests/test_model.py

Previously indexing an array symbol by a mixture of arrays, integers, and non-empty slices would always result in an error.

Fix combined indexing

---

dwave/optimization/src/nodes/indexing.cpp
releasenotes/notes/support-scalar-indices-with-advanced-indexing-027ad8cee2a4d2a5.yaml
tests/cpp/tests/test_nodes_indexing.cpp

This should achieve the expected behavior for scalar (0-dimensional) `ArrayNode` indices for `AdvancedIndexingNode`. Previously there were a few asserts and an exception raised in one case but it was not properly prevented, and also not properly implemented.

Fix behavior for scalar indices in adv indexing

---

dwave/optimization/src/nodes/indexing.cpp
tests/cpp/tests/test_nodes_indexing.cpp

In the `AdvancedIndexingNode`, when handling main array updates, if there was an update to an index that was not covered by the just-parsed updates to indexing arrays, then a function to break the index into its main offset and "sub array index" (called `get_mapped_index`) would segfault if the indexing arrays were not 1d. This went unnoticed by the fixes in #112 because we forgot to test this special kind of update on the main array.
It was all right there in my own `NOTE:` :smiling_face_with_tear:

Fix bug in AdvInd propagation when handling non-1d indexing arrays

---

dwave/optimization/src/nodes/indexing.cpp
releasenotes/notes/advanced-indexing-disallow-higher-than-1d-indexers-5ffcd3fc9541f079.yaml
tests/cpp/tests/test_nodes_indexing.cpp
tests/test_symbols.py

Larger than 1d is still not well tested

Prevent higher dim indexers for advanced indexing

---

dwave/optimization/mathematical.py

A couple of minute typo fixes in the docstring for `dwave.optimization.mathematical.where`.

Fix `where` docstring in` mathematical.py`

---

dwave/optimization/libcpp/graph.pxd
dwave/optimization/model.pyi
dwave/optimization/src/nodes/indexing.cpp
dwave/optimization/symbols.pyx
releasenotes/notes/feature-better-indexing-error-messages-2e2ce0e2bbebb42e.yaml
tests/test_symbols.py

In the case of combined indexing the reported axis might be a bit confusing. But combined with the traceback I think it's fairly clear what's happening.

Raise better error messages from indexing arrays

---

docs/intro.rst

Thanks again to Gaelen for noticing this typo.

Fix typo in caption (explicit --> implicit)

---

dwave/optimization/symbols.pyx

Currently:
Fix:
Should be last one from Gaelen in the series

Fix formatting for math formula of DisjointBitSets class method

---

dwave/optimization/src/nodes/indexing.cpp
releasenotes/notes/fix-bugs-in-advanced-indexing-non-const-array-with-dynamic-indexers-1ef4c31adebcc081.yaml
tests/cpp/tests/test_nodes_indexing.cpp

First one was just a simple logic error in which method should be called when reverting the reverse offset map. Second one was basically covered by an old TODO: to ensure all updates to the parent array are reflected in the final advanced indexing output, we need to track the offset indices that were modified (not just the offsets themselves) as new offsets may be added that duplicate previous unchanged offsets.

Fix two bugs in advanced indexing propagation for non-const non-dynamic arrays with dynamic indexers

---

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/src/nodes/_state.hpp
dwave/optimization/src/nodes/mathematical.cpp
dwave/optimization/src/nodes/testing.cpp
releasenotes/notes/UnaryOpNode-dynamic-predecessor-f7cd282afb15270d.yaml
tests/cpp/tests/test_nodes_mathematical.cpp

Previously it would accept them but then segfault.

Update `UnaryOpNode` to correctly handle dynamic predecessors

---

dwave/optimization/generators.py
releasenotes/notes/change-job-shop-scheduling-generator-f47e34d5a03deb6e.yaml
tests/test_generators.py

Removed the redundant ordering list variable at the price of adding O(N^2) disjunctive constraints between all pairs of job on each machine.

Changed formulation of JSSP

---

.circleci/config.yml

We want to test the C++ code with several gcc versions. In each case we let the docker image determine the Python version used for meson etc.

Test C++ code with gcc11-14

---

dwave/optimization/include/dwave-optimization/array.hpp
releasenotes/notes/fix-ArrayIterator-9eb71f75a968f570.yaml
tests/cpp/test_array.cpp

See also [C.12: Don’t make data members const or references in a copyable or movable type](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c12-dont-make-data-members-const-or-references-in-a-copyable-or-movable-type)

Refactor C++ `ArrayIterator` for performance and safety

---

requirements.txt

To the latest as of today. A user was experiencing a bug with the previous version(s). If we find ourselves doing this too often we can switch to `~=1.0`.

Update build requirements in requirements.txt

---

docs/reference/models.rst
dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/include/dwave-optimization/nodes/collections.hpp
dwave/optimization/libcpp/graph.pxd
dwave/optimization/model.pyi
dwave/optimization/model.pyx
dwave/optimization/src/graph.cpp
releasenotes/notes/feature-remove-unused-symbols-5ad976d5935e417c.yaml
tests/cpp/test_graph.cpp
tests/test_model.py

Closes https://github.com/dwavesystems/dwave-optimization/issues/41

Add methods to remove unused symbols from a model

---

dwave/optimization/generators.py

@axel-GHB noticed that flow shop definitions of m,n (machines & jobs) are reversed: [Taillard's flow shop ](http://mistic.heig-vd.ch/taillard/problemes.dir/ordonnancement.dir/flowshop.dir/tai20_5.txt) provides matrices of machines by jobs while with [JSS](http://mistic.heig-vd.ch/taillard/problemes.dir/ordonnancement.dir/jobshop.dir/tai100_20.txt) it's jobs by machines

Fix flow shop switched ``n`` x ``m`` definitions

---

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/src/nodes/mathematical.cpp
releasenotes/notes/BinaryOpNode-sizeinfo-ac3a01130d77efcc.yaml
tests/cpp/nodes/mathematical/test_binaryop.cpp

This incidentally fixes a serialization bug.
https://github.com/dwavesystems/dwave-optimization/pull/168 has a broader fix, but this one is simple enough that I think it makes sense to do separately.

Implement `BinaryOpNode::sizeinfo()`

---

dwave/optimization/include/dwave-optimization/array.hpp
dwave/optimization/src/nodes/mathematical.cpp
releasenotes/notes/iterator-refactor-7c21470cc6a232c9.yaml
tests/cpp/test_array.cpp

Almost a complete refactor of `ArrayIterator`. Highlights:
* `const` and non-`const` iterators.
* Moved the implementation to be a nested class inside `Array`.
* Made it a random access iterator.

Refactor ArrayIterator for random access and clearer const/non-const

---

README.rst

This way I can stop [linking dimod](https://github.com/dwavesystems/dwave-optimization/pull/169#issuecomment-2483516712).

Update README's Contributing section with Release Note subsection

---

dwave/optimization/libcpp/array.pxd
dwave/optimization/libcpp/graph.pxd
dwave/optimization/libcpp/nodes.pxd
dwave/optimization/libcpp/state.pxd
dwave/optimization/symbols.pxd
dwave/optimization/symbols.pyx

`distutils` is long-since deprecated and we use `meson` to build our files now anyway.

Remove old distutils file headers

---

docs/reference/math.rst
docs/reference/models.rst
dwave/optimization/mathematical.py
dwave/optimization/model.py

The main benefit is that new methods etc are automatically incorporated into the docs.
Similar to https://github.com/dwavesystems/dwave-optimization/pull/73, except for the other classes.

Flatten the docs for Model, State, and mathematical functions

---

dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/src/graph.cpp
releasenotes/notes/Graph-constructor-assignment-20de69b40825424b.yaml
tests/cpp/test_graph.cpp

Use better practices. I.e.
* Mark the relevant methods as `noexcept`. See [C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c66-make-move-operations-noexcept).
* Explicitly disallow copy construction/assigment. This never worked so better to be explicit about it.
* Implement the [rule of five](https://en.cppreference.com/w/cpp/language/rule_of_three).
* Add a few explicit tests.
* Move the definitions into the header. See also [this stackoverflow thread](https://stackoverflow.com/questions/62580224/should-functions-declared-with-default-only-go-in-the-header-file).

Fixup C++ Graph constructors and assignement operators

---

dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/include/dwave-optimization/nodes/collections.hpp
dwave/optimization/include/dwave-optimization/nodes/constants.hpp
dwave/optimization/src/graph.cpp
dwave/optimization/src/nodes/constants.cpp

A slight tidying of some `::update()` methods. IMO it makes sense to do this as an intermediate step while still contemplating https://github.com/dwavesystems/dwave-optimization/issues/188.

Mark Decision::update() and ConstantNode::update() as noreturn

---

dwave/optimization/mathematical.py
tests/test_symbols.py

`concatenate()` should handle a numpy object array of symbols

Fix for issue 190

---

docs/Doxyfile
dwave/optimization/include/dwave-optimization/array.hpp

Mostly just exposed existing docs to sphinx, as well as corrected any obvious errors.
This is not meant to be the final pass.

Add very basic documentation for C++ Array class

---

dwave/optimization/include/dwave-optimization/array.hpp
dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/include/dwave-optimization/nodes/constants.hpp
dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
dwave/optimization/include/dwave-optimization/nodes/testing.hpp
dwave/optimization/src/array.cpp
dwave/optimization/src/graph.cpp
dwave/optimization/src/nodes/manipulation.cpp
dwave/optimization/src/nodes/mathematical.cpp
dwave/optimization/src/nodes/quadratic_model.cpp
tests/cpp/nodes/mathematical/test_binaryop.cpp
tests/cpp/nodes/mathematical/test_naryop.cpp
tests/cpp/nodes/mathematical/test_reduce.cpp
tests/cpp/nodes/mathematical/test_unaryop.cpp
tests/cpp/nodes/test_manipulation.cpp
tests/cpp/test_array.cpp
tests/cpp/test_graph.cpp
tests/cpp/test_utils.cpp

While we don't require files to be formatted to be merged, it is nice to go back to ground every so often.
This PR makes no functional changes, but runs everything through `clang-format`.

Format all C++ files with clang-format

---

dwave/optimization/symbols.pyx

Currently renders like this:
Updated to:

Fix `sqrt()` example formatting

---

meson.build
meson.options

Tests can be disabled with
```bash
meson setup build -Dbuild-tests=disabled
```
by default the tests are built when the `buildtype` is not `release`.

Add a meson build option to enable/disable/auto tests

---

subprojects/catch2.wrap
tests/cpp/nodes/indexing/test_advanced.cpp
tests/cpp/nodes/indexing/test_basic.cpp
tests/cpp/nodes/mathematical/test_binaryop.cpp
tests/cpp/nodes/mathematical/test_reduce.cpp
tests/cpp/nodes/mathematical/test_unaryop.cpp
tests/cpp/nodes/test_collections.cpp
tests/cpp/nodes/test_constants.cpp
tests/cpp/nodes/test_flow.cpp
tests/cpp/nodes/test_manipulation.cpp
tests/cpp/nodes/test_numbers.cpp
tests/cpp/nodes/test_quadratic_model.cpp
tests/cpp/test_array.cpp
tests/cpp/test_utils.cpp

The upshot is that the newer `Catch2`s let you do
```c++
CHECK_THAT(lhs, RangeEquals({0, 1, 2}));
```
rather than
```c++
CHECK(std::ranges::equal(lhs, std::vector{0, 1, 2}));
```
this is a bit more succinct, and it actually gives a useful error message when they don't match!
```../tests/cpp/nodes/mathematical/test_binaryop.cpp:228: FAILED:
CHECK_THAT( le_ptr->shape(), RangeEquals({5, 7}) )
with expansion:
{ 5 } elements are { 5, 7 }
```
This PR has no functional changes, but IMO makes for much cleaner test code.
I am also sure I missed a few, but not trying to be 100% complete.

Use catch2 v3.8.0 for C++ testing

---

dwave/optimization/include/dwave-optimization/array.hpp
dwave/optimization/include/dwave-optimization/nodes/collections.hpp
dwave/optimization/include/dwave-optimization/nodes/constants.hpp
dwave/optimization/include/dwave-optimization/nodes/flow.hpp
dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
dwave/optimization/include/dwave-optimization/nodes/testing.hpp
dwave/optimization/src/array.cpp
dwave/optimization/src/nodes/collections.cpp
dwave/optimization/src/nodes/constants.cpp
dwave/optimization/src/nodes/flow.cpp
dwave/optimization/src/nodes/indexing.cpp
dwave/optimization/src/nodes/manipulation.cpp
dwave/optimization/src/nodes/mathematical.cpp
dwave/optimization/src/nodes/numbers.cpp
dwave/optimization/src/nodes/testing.cpp
releasenotes/notes/Array.minmax-6de0b413d2c77b4c.yaml
tests/cpp/nodes/mathematical/test_binaryop.cpp
tests/cpp/nodes/mathematical/test_naryop.cpp
tests/cpp/nodes/mathematical/test_reduce.cpp
tests/cpp/nodes/mathematical/test_unaryop.cpp

Changes the ways that C++ ``Array`` subclasses propagate their minimum and maximum possible values. Nodes now should implement a single ``::minmax()`` method. That method is then called from ``Array::min()`` and ``Array::max()``.
The ``::minmax()`` function also optionally accepts a ``cache`` argument. It can be passed in using the `cache_type` type alias. E.g.,
```c++
Array::cache_type<std::pair<double, double>> cache;
const auto [low, high] = node_ptr->minmax(cache);
```
Closes https://github.com/dwavesystems/dwave-optimization/issues/182

Add `Array::minmax()` method

---

dwave/optimization/_model.pyi
dwave/optimization/_model.pyx
dwave/optimization/model.py
dwave/optimization/states.pyi
dwave/optimization/states.pyx
tests/test_model.py
tests/test_states.py

The first of a series of serialization PRs to support v1. This one is mostly focused on tidying the existing code to make later PRs easier to review.
The only functional change is the addition of a `version` keyword argument for `to_file()`. I also did some test reorganization which will help the followup PRs.
I'll add a release note once the `version` keyword argument actually does something.
See also https://github.com/dwavesystems/dwave-optimization/issues/223

Tidy serialization code and tests

---

dwave/optimization/src/nodes/mathematical.cpp
tests/cpp/nodes/mathematical/test_binaryop.cpp

We do not need the lhs of a divide operation to be nonzero. Added a test to trigger the case.
No release note because the `asserts` are not turned on in release versions of the solver.

Remove some erroneous asserts

---

dwave/optimization/src/nodes/manipulation.cpp
releasenotes/notes/fix-ConcatenateNode-updates-f5eef8f7efda3879.yaml
tests/cpp/nodes/test_manipulation.cpp

Previously it would incorrectly indicate the changed value was from the beginning of each subsection.

Fix ConcatenateNode propagation

---

dwave/optimization/src/nodes/indexing.cpp
releasenotes/notes/fix-basic-indexing-static-size-or-simple-domain-propagation-442b3563091f54f7.yaml
tests/cpp/nodes/indexing/test_basic.cpp

During basic indexing propagation when the predecessor array is statically sized or both the start and stop are positive, we do a basic translation of indices of the updates and otherwise pass them through. We also calculate the start and stop of the "domain" of the basic indexing operation in terms of indices on the predecessor array, and then exclude updates that are outside of this domain. The stop of this domain was calculated by subtracting the pointers returned by `end()` and `begin()`. However, if the start of the domain is not zero, this stop index will not be correct, and thus some updates may get excluded that should not be. Fixed by subtracting the predecessor array's `begin()` from the basic indexing node's `end()` to get the true stop index.

Fix bug in basic indexing propagation

---

dwave/optimization/src/nodes/indexing.cpp
tests/cpp/nodes/indexing/test_advanced.cpp
tests/cpp/nodes/indexing/test_basic.cpp

Previous logic worked for only for non-trivial slices on the first dimension

Fix the "index filter" for BasicIndexing propagation

---

dwave/optimization/_model.pyi
dwave/optimization/_model.pyx
dwave/optimization/states.pyi
dwave/optimization/states.pyx
dwave/optimization/utilities.py
tests/test_model.py

These are used in https://github.com/dwavesystems/dwave-optimization/pull/241, but are not really serialization-specific. So to make that PR easier to review IMO it makes sense to break them out.
The existing testing covers it pretty well, hence no new tests.

Add some utility decorators for Model/States methods

---

dwave/optimization/_model.pyx
dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/libcpp/graph.pxd
releasenotes/notes/deterministic-node-method-a74d4c8a8e5f8300.yaml
tests/cpp/nodes/mathematical/test_binaryop.cpp
tests/cpp/nodes/test_collections.cpp
tests/cpp/nodes/test_numbers.cpp
tests/utils.py

We want to be able to support intermediate nodes with non-deterministic states while serializing. See https://github.com/dwavesystems/dwave-optimization/pull/241.

Add Node::deterministic_state() method

---

.circleci/config.yml
dwave/optimization/_model.pyi
dwave/optimization/_model.pyx
tests/test_serialization.py

In CI confirm that models/states serialized with modern `dwave-optimization` are compatible with models/states from [0.5.2](https://github.com/dwavesystems/dwave-optimization/releases/tag/0.5.2) - the last version that only supported serialization version 0.1.

Test serialization in CI

---

dwave/optimization/include/dwave-optimization/nodes/lp.hpp
dwave/optimization/src/nodes/lp.cpp
tests/cpp/nodes/test_lp.cpp

LPNode is no longer an ArrayNode, allowing the user to pick which of the outputs (solution, feasibility, objective) are needed in the model.

Add LPNodeBase ABC and LPSolutionNode

---

dwave/optimization/include/dwave-optimization/graph.hpp
dwave/optimization/include/dwave-optimization/nodes/numbers.hpp
dwave/optimization/src/graph.cpp
releasenotes/notes/simple-propagation-b352e157e95dd8d6.yaml
tests/cpp/test_graph.cpp

I have not touched the existing methods, though probably at some point we should switch them over to using `std::ranges::for_each(...)` as well.

Add simple propagation overloads

---

dwave/optimization/include/dwave-optimization/array.hpp
dwave/optimization/include/dwave-optimization/nodes/lp.hpp
dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
dwave/optimization/src/nodes/_state.hpp
dwave/optimization/src/nodes/lp.cpp
dwave/optimization/src/nodes/manipulation.cpp

Removes a fair amount of code duplication.
Could be replicated for `ArrayOutputMixin`, but IMO we should play with this one for a while first.
One thing that this is highlighting for me is that we have a circular dependency between `array.hpp` and `graph.hpp`. We've gotten around it for now by messing with templates and the like, but probably there are nicer things we could do in the future.

Add default state support to `ScalarOutputMixin`

---

dwave/optimization/include/dwave-optimization/array.hpp
dwave/optimization/src/nodes/manipulation.cpp
tests/cpp/test_array.cpp

Otherwise compilation fails on some compilers that seem not to include cstdint implicitly

Include <cstdint> on all files that use std::int*_t

---

dwave/optimization/include/dwave-optimization/array.hpp

Small followup on https://github.com/dwavesystems/dwave-optimization/pull/271

Make ScalarOutputMixinStateData available to all classes that inherit from ScalarOutputMixin

---

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp
dwave/optimization/src/nodes/mathematical.cpp

Rather than merely tracking the type, they now hold an instantiated functional object. This allows for statefull operations in the future.
This is required for say #290

Update mathematical nodes to hold their op

---

dwave/optimization/_model.pyx
dwave/optimization/symbols.pyx

Many symbols don't actually need to hold a pointer of their specific type. We can remove a lot of boilerplate from such symbols.

Remove symbol construction boilerplate from many symbols

---

dwave/optimization/src/nodes/mathematical.cpp
releasenotes/notes/binaryopnode-support-both-predecessors-dynamic-096fc6daa7c0fe0b.yaml
tests/cpp/nodes/mathematical/test_binaryop.cpp

This is not an optimal implementation for handling the dynamic case with both parents having updates, but I tried to strike a balance between efficiency and keeping the changes minimal (by using `deduplicate_diff()`, even though it preserves the update values we don't care about).

Support two dynamic predecessors for BinaryOp

---

dwave/optimization/include/dwave-optimization/nodes/indexing.hpp
dwave/optimization/src/nodes/indexing.cpp
releasenotes/notes/fix-adv-indexing-dynamic-shape-8ad943e35d22cccd.yaml

Previously, `AdvancedIndexingNode` kept an array as an attribute to hold the shape in the dynamic case (when indexing arrays have a dynamic size).
However, this could lead to inconsistent reported shape when mutating multiple states. Fixed by moving the shape data to live on the node state data, just like `BasicIndexingNode`.

Move AdvancedIndexingNode's shape to node state data

---

dwave/optimization/src/graph.cpp

Calling `Graph::recursive_reset()` on a graph with many successive diamonds would previously be very slow to due the combinatorial explosion of paths through the graph.

Fix expensive resursion in Graph::recursive_reset()

---

dwave/optimization/include/dwave-optimization/nodes/statistics.hpp
dwave/optimization/libcpp/nodes.pxd
dwave/optimization/mathematical.py
dwave/optimization/src/nodes/statistics.cpp
dwave/optimization/symbols.pyx
meson.build
releasenotes/notes/mean-symbol-932d07bdd51f738b.yaml
tests/cpp/meson.build
tests/cpp/nodes/test_statistics.cpp
tests/test_symbols.py

Basic implementation of numpy.mean() without axis arguments. Fix #238.

Add MeanNode/Symbol

---

dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp
dwave/optimization/libcpp/nodes.pxd
dwave/optimization/mathematical.py
dwave/optimization/src/nodes/manipulation.cpp
dwave/optimization/symbols.pyx
releasenotes/notes/feature-broadcasting-773034ff391baf44.yaml
tests/cpp/nodes/test_manipulation.cpp
tests/test_mathematical.py
tests/test_symbols.py

Note that we don't (yet) support implicit broadcasting. Only explicit. The reason is to avoid excessive duplicate symbol creation. In the future we should add caching and/or a way to remove duplicate symbols.
Closes https://github.com/dwavesystems/dwave-optimization/issues/15

Add broadcasting support

---

.circleci/config.yml

Trying to reduce the total amount of CI time.
For now, rather than testing all GCC versions, we instead test min and max.
Also, do the C++23 and C++20 tests within the same job to reuse the time installing python etc.

Generate fewer C++ CI tests

---

dwave/optimization/include/dwave-optimization/iterators.hpp
dwave/optimization/include/dwave-optimization/typing.hpp
releasenotes/notes/bool-iterator-7a49134458f91e50.yaml
tests/cpp/test_iterators.cpp

Still a ways to go before we can have truly types arrays, but we need this for boolean arrays.
It does have the side effect that we'll need to do something about the `std::vector<bool>` overload.

Add C++ support for bool dtype

---

dwave/optimization/include/dwave-optimization/nodes/set_routines.hpp
dwave/optimization/libcpp/nodes/__init__.pxd
dwave/optimization/libcpp/nodes/set_routines.pxd
dwave/optimization/mathematical.py
dwave/optimization/src/nodes/set_routines.cpp
dwave/optimization/symbols/__init__.py
dwave/optimization/symbols/set_routines.pyi
dwave/optimization/symbols/set_routines.pyx
meson.build
releasenotes/notes/isin-symbol-0980669e07396b4c.yaml
tests/cpp/meson.build
tests/cpp/nodes/test_set_routines.cpp
tests/test_symbols.py

Initial minimal implementation of [numpy.isin() ](https://numpy.org/doc/stable/reference/generated/numpy.isin.html#numpy.isin) using lookup tables. Fixes #76. Given that this fixes an old issue, I wanted to check which functionality from [numpy.isin()](https://numpy.org/doc/stable/reference/generated/numpy.isin.html#numpy.isin) we should port over for this node. Should this node include any of the following?
1. `bool assume_unique` (kwarg)
2. `bool invert` (kwarg)
3. `kind {None, sort, table}` (kwarg)
Regarding 2, I believe this could just be done with the EqualNode. For example:
```
>>> from dwave.optimization.model import Model
>>> from dwave.optimization.mathematical import isin
>>> model = Model()
>>> model.states.resize(1)
>>> element = model.constant([1.3, -1.0, 3.0])
>>> …
```

Add IsInNode/Symbol

---

dwave/optimization/src/nodes/lambda.cpp
releasenotes/notes/fix-AccumulateZip-expression-input-initialization-a48a45b701f4d46c.yaml
tests/cpp/nodes/test_lambda.cpp

Previously AccumulateZip would initialize the inputs in an expression their `min()` value, but since it is common that we have unbounded inputs (i.e. `min()` returns `-inf`) this could result in NaNs being created/propagated in the expression during evaluation, causing other issues. This is fixed by just initializing the inputs close to 0.

Fix potential issue with expression input init in AccumulateZipNode
