dwave/optimization/model.pyx, tests/test_model.py
=> Fix model unlock on exception

docs/intro.rst
=> Rescale blurred images

docs/intro.rst, dwave/optimization/mathematical.py, dwave/optimization/model.pyx, dwave/optimization/symbols.pyx
I'll likely change some of these but this PR is to fix the failing automated tests for when those are turned on.
=> Fix failing tests

docs/reference/generators.rst, dwave/optimization/generators.py, releasenotes/notes/add-quadratic-assignment_generator-6955619da329e057.yaml, tests/test_generators.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/29
=> Add quadtratic assignment problem generator

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp, releasenotes/notes/fix-ArraySymbol.all-adc9381c654b1d1d.yaml, tests/test_symbols.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/43
Also adds testing for the other reduce nodes.
=> Add identity value for ArraySymbol.all()

dwave/optimization/model.pyx, dwave/optimization/symbols.pyx
Break the whitefix fix from https://github.com/dwavesystems/dwave-optimization/pull/49 into its own PR.
=> Remove trailing spaces

dwave/optimization/model.pyx, dwave/optimization/symbols.pyx, releasenotes/notes/maybe_equals-return-type-dd06bd6f8b2f31f3.yaml, tests/test_symbols.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/23
=> Make `maybe_equals` consistently return integers

dwave/optimization/include/dwave-optimization/graph.hpp, dwave/optimization/include/dwave-optimization/nodes/collections.hpp, dwave/optimization/include/dwave-optimization/nodes/constants.hpp, dwave/optimization/include/dwave-optimization/nodes/indexing.hpp, dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp, dwave/optimization/include/dwave-optimization/nodes/numbers.hpp, dwave/optimization/include/dwave-optimization/nodes/quadratic_model.hpp, dwave/optimization/include/dwave-optimization/nodes/testing.hpp, dwave/optimization/libcpp/array.pxd, dwave/optimization/libcpp/graph.pxd, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/model.pxd, dwave/optimization/model.pyx, dwave/optimization/src/graph.cpp, dwave/optimization/src/nodes/collections.cpp, dwave/optimization/src/nodes/indexing.cpp, dwave/optimization/src/nodes/mathematical.cpp, dwave/optimization/src/nodes/quadratic_model.cpp, dwave/optimization/src/nodes/testing.cpp, dwave/optimization/symbols.pxd, dwave/optimization/symbols.pyx, releasenotes/notes/arraynode-24e526957bcdf636.yaml, tests/cpp/tests/test_examples.cpp, tests/cpp/tests/test_nodes_mathematical.cpp
Closes https://github.com/dwavesystems/dwave-optimization/issues/75 by implementing the virtual inheritance pattern.
=> Promote ArrayNode from a concept to a full subclass

docs/reference/math.rst, dwave/optimization/include/dwave-optimization/array.hpp, dwave/optimization/include/dwave-optimization/graph.hpp, dwave/optimization/include/dwave-optimization/nodes/flow.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/mathematical.py, dwave/optimization/src/graph.cpp, dwave/optimization/src/nodes/flow.cpp, dwave/optimization/src/nodes/testing.cpp, dwave/optimization/symbols.pyi, dwave/optimization/symbols.pyx, releasenotes/notes/where-node-3d6519b7d78ecb03.yaml, tests/cpp/tests/test_flow.cpp, tests/test_symbols.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/66
This is currently rebased off of https://github.com/dwavesystems/dwave-optimization/pull/74. Will either remove that dependency ore merge https://github.com/dwavesystems/dwave-optimization/pull/74 before marking this as ready to review.
=> Add `Where` symbol

dwave/optimization/include/dwave-optimization/array.hpp, releasenotes/notes/fix-array-min-ee4c2b1010a21162.yaml, tests/cpp/tests/test_array.cpp
Closes https://github.com/dwavesystems/dwave-optimization/issues/85
=> Fix `Array::min()`

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp, dwave/optimization/include/dwave-optimization/nodes/numbers.hpp, dwave/optimization/src/nodes/_state.hpp, dwave/optimization/src/nodes/flow.cpp, dwave/optimization/src/nodes/mathematical.cpp, releasenotes/notes/binary-op-scalar-broadcasting-b7b3d1906da45dea.yaml, tests/cpp/tests/test_nodes_mathematical.cpp, tests/test_symbols.py
This is a very limited form of https://github.com/dwavesystems/dwave-optimization/issues/15, but a common one.
=> Support scalar broadcasting for binary operations

tests/cpp/tests/test_nodes_mathematical.cpp
The mathematical nodes were not very consistently organized. So this PR somewhat fixes that. No tests have been added or removed. Purely moves stuff around.
No functional change.
=> Reorganize C++ mathematical nodes tests

docs/intro.rst
Previously there was a mix of tabs and spaces, but only in a few sections.
Content it unchanged. It renders identically to before.
=> Fix whitespace in `intro.rst`

dwave/optimization/src/nodes/mathematical.cpp, tests/cpp/tests/test_nodes_mathematical.cpp
Doesn't need a release note, because it's covered on the release note already added in https://github.com/dwavesystems/dwave-optimization/pull/115
=> Implement `SumNode.min()` and `SumNode.max()` for dynamic predecessors

dwave/optimization/generators.py, releasenotes/notes/add-CVRPTW-generator-9315a2fe767d934a.yaml, tests/test_generators.py
Created this PR to drop PR #107
=> Add CVRPTW generator

dwave/optimization/__init__.py
Incorporate the release branch for https://github.com/dwavesystems/dwave-optimization/releases/tag/0.4.2 back into `main`.
=> Update version 0.4.2.dev -> 0.4.2

dwave/optimization/include/dwave-optimization/array.hpp, dwave/optimization/src/array.cpp, releasenotes/notes/View-convenience-57d9c519201b941e.yaml, tests/cpp/test_array.cpp
As well as some other minor refactors and testing.
I wrote these while working on some experiments and thought they might be more generally useful.
=> Add some convenience methods to `Array::View`

.circleci/config.yml, docs/Doxyfile, docs/Makefile, docs/conf.py, docs/reference/cpp.rst, docs/requirements.txt
The docs are hideous and far from complete, but they do build. A reasonable first step.
=> Build C++ docs, but do not include them in any toctrees

dwave/optimization/mathematical.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/204
=> Fix stack() example formatting

dwave/optimization/mathematical.py, dwave/optimization/symbols.pyi, dwave/optimization/symbols.pyx, releasenotes/notes/fix-symbols-import-96d850c767eab38c.yaml, tests/test_symbols.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/193
=> Minor fixes

dwave/optimization/include/dwave-optimization/nodes/constants.hpp, dwave/optimization/include/dwave-optimization/nodes/manipulation.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/mathematical.py, dwave/optimization/src/nodes/_state.hpp, dwave/optimization/src/nodes/manipulation.cpp, dwave/optimization/symbols.pyx, releasenotes/notes/feature-Put-f07f543015dd2ed8.yaml, tests/cpp/nodes/test_manipulation.cpp, tests/test_symbols.py
Following [numpy.put()](https://numpy.org/doc/2.1/reference/generated/numpy.put.html). Though we return a new array rather than mutating in-place.
Closes https://github.com/dwavesystems/dwave-optimization/issues/202
=> Add ability to insert values into an array symbol

tests/cpp/test_utils.cpp
Running locally, this PR reduces the runtime from ~5s to ~.1s.
=> Improve the runtime of C++ tests

docs/reference/symbols.rst, dwave/optimization/_model.pyx
See also: https://github.com/dwavesystems/dwave-optimization/pull/73, https://github.com/dwavesystems/dwave-optimization/pull/183. This should be the last of that series.
=> Flatten Symbol and ArraySymbol docs

dwave/optimization/src/nodes/manipulation.cpp, releasenotes/notes/fix-concatenate-minmax-cache-4a9fe2418b6ab432.yaml, tests/cpp/nodes/test_manipulation.cpp
Accidentally missed in https://github.com/dwavesystems/dwave-optimization/pull/229
=> Fix ConcatenateNode::minmax()

dwave/optimization/_model.pyx
No functional change.
A reorganization that is used by https://github.com/dwavesystems/dwave-optimization/pull/241
=> Implement separate private methods for managing the header when (de)serializing

dwave/optimization/src/simplex.cpp, dwave/optimization/src/simplex.hpp, meson.build, tests/cpp/meson.build, tests/cpp/test_simplex.cpp
First pass so we can at least start to see what a good interface will look like. <s>Appears to be correct based on the three tiny tests I wrote :smile: </s>
Tested on the [netlib lb instances](https://github.com/scipy/scipy/tree/06712cfa85033d445408f9ee898e4954375a0aa1/benchmarks/benchmarks/linprog_benchmark_files) including the infeasible problems. Results match `scipy.optimize.linprog(method="simplex")`. Reasonably confident that it is correct.
=> Simple simplex implementation

dwave/optimization/include/dwave-optimization/nodes/lp.hpp, dwave/optimization/src/nodes/lp.cpp
And handle null solution (for the case of infeasibility or no updates).
=> LPSolutionNode: clip output

dwave/optimization/include/dwave-optimization/nodes/lp.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/src/nodes/lp.cpp, dwave/optimization/symbols.pxd, dwave/optimization/symbols.pyi, dwave/optimization/symbols.pyx, tests/test_symbols.py
Still need docstrings <s>and serialization</s>
=> LP symbols

dwave/optimization/mathematical.py, dwave/optimization/symbols.pyx, releasenotes/notes/feature-linprog-4ae1cd2f12c021f4.yaml, tests/test_symbols.py
The docstring definitely needs even more, but this should suffice as an MVP.
=> Add `linprog()` function

dwave/optimization/include/dwave-optimization/nodes/lp.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/mathematical.py, dwave/optimization/src/nodes/lp.cpp, dwave/optimization/symbols.pxd, dwave/optimization/symbols.pyi, dwave/optimization/symbols.pyx, releasenotes/notes/add-lp-symbol-f041b12d7f75cbfe.yaml, tests/cpp/nodes/test_lp.cpp, tests/test_symbols.py
No functional changes, but hopefully a clearer (and final) name
=> Rename LP -> LinearProgram and LPNode -> LinearProgramNode

.circleci/config.yml, pyproject.toml, requirements.txt
A bit of maintenance. No functional changes, just moving to the latest and making `requirements.txt` and `pyproject.toml` consistent with eachother.
=> Update build dependency versions

dwave/optimization/mathematical.py, dwave/optimization/symbols.pyx, releasenotes/notes/feature-absolute-716cc20fc7a5d725.yaml, tests/test_symbols.py
Adds no new functionality. Just adds an alias. The primary benefit is better documentation.
=> Add absolute function

dwave/optimization/_utilities.pxd, dwave/optimization/_utilities.pyx, dwave/optimization/libcpp/__init__.pxd, dwave/optimization/libcpp/array.pxd, dwave/optimization/libcpp/graph.pxd, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/symbols.pyx, pyproject.toml, requirements.txt
~Will rebase off of https://github.com/dwavesystems/dwave-optimization/pull/279 once it's merged.~ Done
=> Build with Cython 3.1

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/mathematical.py, dwave/optimization/src/nodes/mathematical.cpp, dwave/optimization/symbols.pyx, releasenotes/notes/feature-safe-divide-e49a7c268c4f4de9.yaml, tests/cpp/nodes/mathematical/test_binaryop.cpp, tests/test_symbols.py
Closes https://github.com/dwavesystems/dwave-optimization/issues/290
=> Add `SafeDivide` symbol

docs/index.rst, docs/philosophy.rst, dwave/optimization/_model.pyx
Closes https://github.com/dwavesystems/dwave-optimization/issues/313
=> Fix spelling principals -> principles

dwave/optimization/include/dwave-optimization/array.hpp, dwave/optimization/src/array.cpp, dwave/optimization/src/nodes/mathematical.cpp, dwave/optimization/src/nodes/testing.cpp, releasenotes/notes/view-interface-263c01dc2e6ae1b5.yaml, tests/cpp/test_array.cpp
Turns out `std::ranges::view_interface` will do a lot of the work we did for us.
=> Use std::ranges::view_interface for Array::View

docs/philosophy.rst, dwave/optimization/_model.pyx
Previously we didn't discuss this concept at all, so adding a bit of content that we should expand in the future.
=> Add minimal docs for dynamic array symbols

dwave/optimization/_model.pyx, dwave/optimization/symbols.pyx, releasenotes/notes/constant-promotion-9bc974cd760c83e0.yaml, tests/test_model.py, tests/test_symbols.py
=> Enable constant promotion on arithmetic dunder methods

dwave/optimization/src/nodes/sorting.cpp, tests/cpp/nodes/test_sorting.cpp
=> Fix ArgSortNode::revert

dwave/optimization/include/dwave-optimization/nodes/mathematical.hpp, dwave/optimization/libcpp/nodes.pxd, dwave/optimization/mathematical.py, dwave/optimization/src/nodes/mathematical.cpp, dwave/optimization/symbols.pyx, releasenotes/notes/softmax-symbol-f6508ce3032120f9.yaml, tests/cpp/meson.build, tests/cpp/nodes/mathematical/test_softmax.cpp, tests/test_symbols.py
Fix #281. Basic implementation of softmax (https://en.wikipedia.org/wiki/Softmax_function) without axis arguments. 
I am concerned about errors in doubles due to rounding over time but thought it would be best to get feedback on implementation as is.
=> Add SoftMaxNode/Symbol
